import { db } from "@/lib/db";
import { normalizeShopDomain } from "@/lib/shopify/domain";

export default async function Inventory({ searchParams }: { searchParams: Promise<{ shop?: string; q?: string; status?: string }> }) {
  const p=await searchParams; const domain=normalizeShopDomain(p.shop||""); const q=(p.q||"").trim(); const status=p.status||"all";
  const shop=await db.shop.findUnique({where:{domain}}); if(!shop) return <main className="landing">Boutique introuvable</main>;
  const quantity = status==="out"?{lte:0}:status==="low"?{gt:0,lte:3}:undefined;
  const rows=await db.inventoryLevel.findMany({where:{shopId:shop.id,location:{excluded:false},...(quantity?{availableQty:quantity}:{}),...(q?{variant:{OR:[{sku:{contains:q,mode:"insensitive"}},{barcode:{contains:q,mode:"insensitive"}},{title:{contains:q,mode:"insensitive"}},{product:{title:{contains:q,mode:"insensitive"}}}]}}:{})},include:{location:true,variant:{include:{product:true}}},take:500,orderBy:[{variant:{product:{title:"asc"}}},{variant:{title:"asc"}}]});
  return <div className="shell"><aside className="sidebar"><div className="brand">STOCKIFY</div><a href={`/dashboard?shop=${domain}`}>Tableau de bord</a><a className="active" href={`/inventory?shop=${domain}`}>Inventaire</a></aside><main className="content"><h1>Inventaire</h1><p>Recherche par produit, variante, SKU ou code-barres.</p><form className="toolbar"><input name="shop" type="hidden" value={domain}/><input name="q" defaultValue={q} placeholder="Rechercher…"/><select name="status" defaultValue={status}><option value="all">Tous les stocks</option><option value="low">Stock faible (1–3)</option><option value="out">Rupture</option></select><button>Filtrer</button></form><div className="panel table-wrap"><table className="table"><thead><tr><th>Famille</th><th>Produit</th><th>Couleur</th><th>Taille</th><th>SKU</th><th>Magasin</th><th>Disponible</th><th>On hand</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.variant.product.family||"—"}</td><td>{r.variant.product.title}</td><td>{r.variant.optionColor||"—"}</td><td>{r.variant.optionSize||"—"}</td><td>{r.variant.sku||"—"}</td><td>{r.location.name}</td><td>{r.availableQty}</td><td>{r.onHandQty}</td></tr>)}</tbody></table></div></main></div>;
}
